
server:
  port: 0

spring:
  application:
    name: SessionFunctionService

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone : http://EurekaDiscoveryService:8761/eureka
#      defaultZone : http://i8a703.p.ssafy.io:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}